name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Generate Allure Report
      run: |
        npm run report
        mkdir -p artifacts
        cp -r allure-report/* artifacts/

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: artifacts
